http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  tls:
    enabled: false
    certificate: ""
    key: ""

app:
  name: "Gossip"
  environment: "local"
  encryptionKey: "A,hrAZU}_;cN-}K]e5NcgRtjE}E^[]v~o"
  timeout: "20s"
  passwordToken:
      expiration: "60m"
      length: 64
  emailVerificationTokenExpiration: "12h"

cache:
  capacity: 100000
  expiration:
    staticFile: "4380h"
    page: "24h"

database:
  driver: "sqlite3"
  connection: "dbs/main.db?_journal=WAL&_timeout=5000&_fk=true"
  testConnection: ":memory:?_journal=WAL&_timeout=5000&_fk=true"

queuedatabase:
  driver: "sqlite3"
  connection: "dbs/queue.db?_journal=WAL&_timeout=5000&_fk=true"
  testConnection: ":memory:?_journal=WAL&_timeout=5000&_fk=true"

tasks:
  pollInterval: "1s"
  maxRetries: 10
  goroutines: 1

mail:
  hostname: "localhost"
  port: 25
  user: "admin"
  password: "admin"
  fromAddress: "admin@localhost"
